services:
  # run frontend-prod build
  client:
    image: nish1896/ecom-mern-client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - '3000:80'

  # run client in dev mode with hot reloading
  client-dev:
    image: nish1896/ecom-mern-client-dev
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile.dev
    ports:
      - '3001:3000'
    volumes:
      - '/app/node_modules'
      - './apps/client:/app/apps/client'

  # runs server build
  server:
    image: nish1896/ecom-mern-server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - '8000:8000'

  # server in dev-mode
  server-dev:
    image: nish1896/ecom-mern-server-dev
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile.dev
    ports:
      - '8080:8000'
    volumes:
      - '/app/node_modules'
      - './apps/server:/app/apps/server'
