name: github-actions

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Git Checkout
              uses: actions/checkout@v2

            - name: Setup Node env
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn install

            - name: Build @ecom-mern/shared
              run: yarn build:lib

            - name: Build server
              run: yarn build:server

            - name: Build frontend
              run: yarn build:client

